channel_sources:
  - conda-forge/label/microed-data_dev,conda-forge
channel_targets:
  - conda-forge microed-tools_dev
#c_compiler:           # [win]
#  - m2w64-toolchain   # [win]
#cxx_compiler:         # [win]
#  - m2w64-toolchain   # [win]
#python_c_compiler:    # [win]
#  - vs2015            # [win]
#python_cxx_compiler:  # [win]
#  - vs2015            # [win]
#target_platform:      # [win]
#  - win-64            # [win]
