{% set name = "MicroED tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.1.0-dev.5" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: c3ded05bc4016931eb177f40377e872b62b76b32add3446b56295a82f9f67db7
  patches:
    - 01-setenv.patch
    - 02-install.patch
    - 03-iconv.patch
    - 04-err_h.patch
    - 05-gcc.patch
    - 06-cmake.patch
    - 07-flex.patch
    - 08-cython.patch
    - 09-msvc.patch
    - 10-warnings.patch
    - 11-nlopt-conda.patch  # [win]

build:
  ignore_run_exports:
    - numpy
    - python
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  number: 0
  script_env:
    - USER      # [unix]
    - USERNAME  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake        >=3.15,<4
    - coreutils                 # [unix]
    - cython       >=0.27.1
    - flex         >=2.5.34,<3  # [unix]
    - libxslt      >=0.13.0
    - m2-coreutils              # [win]
    - m2-flex      >=2.5.34,<3  # [win]
    - make                      # [unix]
    - pkg-config                # [unix]
    - vc           14.*         # [win and py>=35 and py<=310]
  host:
    - libiconv                              # [win]
    - libtiff                 4.*
    - libxml2                 >=2.1,<3
    - m2w64-libwinpthread-git               # [win]
    - nlopt                   2.*
    - numpy                   >=1.7,<2
    - python                  {{ python }}
  run:
    - libiconv                                        # [win]
    - {{ pin_compatible('libtiff', max_pin='x.x') }}
    - {{ pin_compatible('libxml2', max_pin='x.x') }}
    - m2w64-libwinpthread-git                         # [win]
    - {{ pin_compatible('nlopt', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('python') }}

test:
  imports:
    - pysmv
  requires:
    - coreutils                         # [unix]
    - m2-coreutils                      # [win]
    - m2-sed                            # [win]
    - microed-data >=0.1.0.dev4,<0.2.0

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert electron diffraction images to SMV format"
  description: |
    The MicroED tools convert sequences of related electron
    diffraction images, or MicroED sweeps, to the Super Marty View
    (SMV) format.

extra:
  recipe-maintainers:
    - hattne
