{% set name = "MicroED tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.1.0-dev.8" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/microed-tools-jiffies-20231107.tar.gz
  sha256: 2208a2a977bb7bdb068f5472f27b35a3c40335e2931ec3dd9829d7675b892ec1
  patches:
    - 01-nlopt-win.patch  # [win]

build:
  ignore_run_exports:
    - numpy
    - python
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [not osx]
  number: 0
  script_env:
    - USER                   # [unix]
    - USERNAME               # [win]
  #skip: True                 # [py==39 and python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake          >=3.18,<4
    - coreutils                           # [unix]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - docbook-xsl
    - flex           >=2.5.34,<3          # [unix]
    - libxslt        >=0.13
    - m2-coreutils                        # [win]
    - m2-sed                              # [win]
    - make                                # [unix]
    - numpy                               # [build_platform != target_platform]
    - pandoc         2.*
    - pkg-config                          # [unix]
    - python                              # [build_platform != target_platform]
    - winflexbison   >=2.2,<3             # [win]
  host:
    - cython         >=0.27.1
    - fftw
    - libarchive     >=3.0.2,<4
    - libiconv                            # [win]
    - libtiff        >=4.5,<5
    - libxml2        >=2.1,<3
    - nlopt          2.*
    - numpy          >=1.7,<2
    #- pthreads-win32                      # [win]
    - python         {{ python }}
  run:
    - fftw
    - libarchive
    - libiconv                            # [win]
    - libtiff
    - libxml2
    - nlopt
    - numpy
    #- pthreads-win32                      # [win]
    - python

test:
  imports:
    - pysmv
  requires:
    - coreutils                         # [unix]
    - m2-coreutils                      # [win]
    - m2-sed                            # [win]
    - microed-data >=0.1.0.dev4,<0.2.0

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert electron diffraction images to SMV format"
  description: |
    The MicroED tools convert sequences of related electron
    diffraction images, or MicroED sweeps, to the Super Marty View
    (SMV) format.

extra:
  recipe-maintainers:
    - hattne
